
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef AGV_MASTER_H
#define AGV_MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 agv_master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * agv_master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data agv_master_Data;

#endif // AGV_MASTER_H
