#ifndef AGVCLIENTCORE_GLOBAL_H
#define AGVCLIENTCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AGVCLIENTCORE_LIBRARY)
#  define AGVCLIENTCORE_EXPORT Q_DECL_EXPORT
#else
#  define AGVCLIENTCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // AGVCLIENTCORE_GLOBAL_H
