
/* File generated by gen_cfile.py. Should not be modified. */

#include "co_master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 agv_master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 agv_master_bDeviceNodeId = 0x10;

/**************************************************************************/
/* Array of message processing information */

const UNS8 agv_master_iam_a_slave = 0;

TIMER_HANDLE agv_master_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 agv_master_obj1000 = 0x0;	/* 0 */
                    subindex agv_master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&agv_master_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 agv_master_obj1001 = 0x0;	/* 0 */
                    subindex agv_master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&agv_master_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 agv_master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 agv_master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t agv_master_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex agv_master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&agv_master_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&agv_master_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 agv_master_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 agv_master_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time. */
                    UNS16 agv_master_obj100C = 500;	/* 256 */
                    subindex agv_master_Index100C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&agv_master_obj100C }
                     };

/* index 0x100D :   Life Time Factor. */
                    UNS8 agv_master_obj100D = 0x1;	/* 256 */
                    subindex agv_master_Index100D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&agv_master_obj100D }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 agv_master_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 agv_master_highestSubIndex_obj1016 = 0;
                    UNS32 agv_master_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 agv_master_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 agv_master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 agv_master_obj1018_Vendor_ID = 0xA7E;	/* 2686 */
                    UNS32 agv_master_obj1018_Product_Code = 0x1;	/* 1 */
                    UNS32 agv_master_obj1018_Revision_Number = 0x1;	/* 1 */
                    UNS32 agv_master_obj1018_Serial_Number = 0x1;	/* 1 */
                    subindex agv_master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&agv_master_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&agv_master_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&agv_master_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&agv_master_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&agv_master_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 agv_master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 agv_master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 agv_master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 agv_master_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex agv_master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&agv_master_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&agv_master_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&agv_master_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&agv_master_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 agv_master_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 agv_master_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 agv_master_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 agv_master_obj1281_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex agv_master_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&agv_master_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&agv_master_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&agv_master_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&agv_master_obj1281_Node_ID_of_the_SDO_Server }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable agv_master_objdict[] = 
{
  { (subindex*)agv_master_Index1000,sizeof(agv_master_Index1000)/sizeof(agv_master_Index1000[0]), 0x1000},
  { (subindex*)agv_master_Index1001,sizeof(agv_master_Index1001)/sizeof(agv_master_Index1001[0]), 0x1001},
  { (subindex*)agv_master_Index100C,sizeof(agv_master_Index100C)/sizeof(agv_master_Index100C[0]), 0x100C},
  { (subindex*)agv_master_Index100D,sizeof(agv_master_Index100D)/sizeof(agv_master_Index100D[0]), 0x100D},
  { (subindex*)agv_master_Index1018,sizeof(agv_master_Index1018)/sizeof(agv_master_Index1018[0]), 0x1018},
  { (subindex*)agv_master_Index1280,sizeof(agv_master_Index1280)/sizeof(agv_master_Index1280[0]), 0x1280},
  { (subindex*)agv_master_Index1281,sizeof(agv_master_Index1281)/sizeof(agv_master_Index1281[0]), 0x1281},
};

const indextable * agv_master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x100C: i = 2;break;
		case 0x100D: i = 3;break;
		case 0x1018: i = 4;break;
		case 0x1280: i = 5;break;
		case 0x1281: i = 6;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &agv_master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status agv_master_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index agv_master_firstIndex = {
  0, /* SDO_SVR */
  5, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index agv_master_lastIndex = {
  0, /* SDO_SVR */
  6, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 agv_master_ObjdictSize = sizeof(agv_master_objdict)/sizeof(agv_master_objdict[0]); 

CO_Data agv_master_Data = CANOPEN_NODE_DATA_INITIALIZER(agv_master);

