#ifndef AGVCLIENTUIEX_GLOBAL_H
#define AGVCLIENTUIEX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AGVCLIENTUIEX_LIBRARY)
#  define AGVCLIENTUIEX_EXPORT Q_DECL_EXPORT
#else
#  define AGVCLIENTUIEX_EXPORT Q_DECL_IMPORT
#endif

#endif // AGVCLIENTUIEX_GLOBAL_H
